# Generated by Django 4.2 on 2024-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0004_alter_product_price_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
